apiVersion: apps/v1
kind: Deployment
metadata:
  name: allunel
  labels:
    app: allunel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allunel
  template:
    metadata:
      labels:
        app: allunel
    spec:
      containers:
      - name: allunel
        image: allunel-pod
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: allunel
  labels:
    app: allunel
spec:
  type: NodePort
  ports:
  - port: 81
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    run: allunel
    component: allunel