apiVersion: apps/v1
kind: Deployment
metadata:
  name: allunel-web
  labels:
    app: allunel-deployment
spec: # deployment
  replicas: 3
  selector:
    matchLabels:
      app: allunel
  template: # replica template
    metadata:
      labels:
        app: allunel
    spec: # pod spec
      containers:
      - name: allunel
        image: allunel-pod
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: allunel-service
  labels:
    app: allunel
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: allunel