apiVersion: apps/v1
kind: Deployment
metadata:
  name: allunel-web
  labels:
    app: allunel
spec: # deployment
  replicas: 1
  selector:
    matchLabels:
      app: allunel
  template: # replica template
    metadata:
      labels:
        app: allunel
    spec: # pod spec
      containers:
      - name: allunel
        image: allunel-pod
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: allunel-service
  labels:
    app: allunel
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: allunel